### ISSUE TITLE
Error in Installation from source.

### ISSUE THREAD

**Issue by jbkoh** [gtfierro/hod#33]
In Ubuntu 16.04 and Go 1.10,
I run:
```
go get -u github.com/gtfierro/hod
```

I get:
```
go build github.com/gtfierro/hod/turtle: invalid flag in #cgo CFLAGS: -L/home/jbkoh/go/src/github.com/gtfierro/hod/turtle
# github.com/immesys/bw2/crypto
In file included from ed25519.c:19:0:
ed25519-randombytes.h:83:26: fatal error: openssl/rand.h: No such file or directory
compilation terminated.
```

so, I installed ``libssl-dev``, and I get:
```
go build github.com/gtfierro/hod/turtle: invalid flag in #cgo CFLAGS: -L/home/jbkoh/go/src/github.com/gtfierro/hod/turtle
```

Looks there is some typo in the installation script.

**Comment by gtfierro** [comment]
This is an issue that was introduced due to changes in cgo for go 1.10 (https://github.com/golang/go/wiki/InvalidFlag). I haven't had time to fix it yet, but you should be able to compile fine using Go 1.9.x

**Comment by jbkoh** [comment]
Thanks!

**Comment by gtfierro** [comment]
https://github.com/gtfierro/hod/commit/b332a8463e53fc52265576c0d43c2b9675097c90

When you get a chance, can you try building Hod with go 1.10 on the latest commit?

**Comment by gtfierro** [comment]
This is fixed
